-- phpMyAdmin SQL Dump
-- version 4.6.6deb5
-- https://www.phpmyadmin.net/
--
-- Client :  localhost:3306
-- Généré le :  Jeu 12 Septembre 2019 à 14:31
-- Version du serveur :  5.7.21-1ubuntu1
-- Version de PHP :  7.2.3-1ubuntu1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `Yugioh`
--

-- --------------------------------------------------------

--
-- Structure de la table `Cartes`
--

CREATE TABLE `Cartes` (
  `Num` varchar(10) CHARACTER SET utf8 DEFAULT NULL,
  `Nom` varchar(46) CHARACTER SET utf8 DEFAULT NULL,
  `Attribut` varchar(8) CHARACTER SET utf8 DEFAULT NULL,
  `Niveau` int(11) DEFAULT NULL,
  `Types` varchar(44) CHARACTER SET utf8 DEFAULT NULL,
  `Attaque` varchar(8) CHARACTER SET utf8 DEFAULT NULL,
  `Defense` varchar(8) CHARACTER SET utf8 DEFAULT NULL,
  `Description` varchar(743) CHARACTER SET utf8 DEFAULT NULL,
  `image_miniature` varchar(60) CHARACTER SET utf8 DEFAULT NULL,
  `image_grande` varchar(60) CHARACTER SET utf8 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Contenu de la table `Cartes`
--

INSERT INTO `Cartes` (`Num`, `Nom`, `Attribut`, `Niveau`, `Types`, `Attaque`, `Defense`, `Description`, `image_miniature`, `image_grande`) VALUES
('dane-fr001', 'Gnomatériel', 'TERRE', 1, '[ Elfe / Effet ]', 'ATK 0', 'DEF 1000', 'Si votre adversaire Invoque Spécialement un ou plusieurs monstres tant que vous ne contrôlez aucune carte : vous pouvez défausser cette carte, puis ciblez 1 monstre face recto contrôlé par votre adversaire ; ce tour, le monstre ne peut être ni Sacrifié ni utilisé comme Matériel pour une Invocation Fusion, Synchro, Xyz ou Lien. Vous ne pouvez utiliser cet effet de \"Gnomatériel\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-1.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-1.jpg'),
('dane-fr002', 'Gardien Pare-Feu', 'TÉNÈBRES', 4, '[ Cyberse / Effet ]', 'ATK 100', 'DEF 2000', 'Si cette carte est envoyée au Cimetière comme Matériel pour l\'Invocation Lien d\'un monstre Cyberse : vous pouvez Invoquer Spécialement cette carte, mais bannissez-la lorsqu\'elle quitte le Terrain. Lorsqu\'une attaque impliquant votre Monstre Lien et un Monstre Lien de l\'adversaire est déclarée : vous pouvez bannir cette carte depuis votre Cimetière ; annulez l\'attaque, et si vous le faites, jusqu\'à la fin de ce tour, l\'ATK d\'origine du monstre de l\'adversaire devient 0, et aussi, il n\'est pas affecté par d\'autres effets de carte (ses propres effets exclus). Vous ne pouvez utiliser chaque effet de \"Gardien Pare-Feu\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-2.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-2.jpg'),
('dane-fr003', 'Balayeur de Grille', 'LUMIÈRE', 4, '[ Cyberse / Effet ]', 'ATK 100', 'DEF 2000', 'Si une Magie de Terrain face recto est dans une Zone Terrain : vous pouvez Invoquer Spécialement cette carte depuis votre main. Vous pouvez bannir cette carte dans votre Cimetière et 1 Monstre Lien que vous contrôlez ; détruisez 1 carte contrôlée par votre adversaire. Vous ne pouvez utiliser chaque effet de \"Balayeur de Grille\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-3.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-3.jpg'),
('dane-fr004', 'Salamangrande Fennec', 'FEU', 3, '[ Cyberse / Effet ]', 'ATK 1600', 'DEF 200', 'Si un ou plusieurs monstres Cyberse que vous contrôlez qui ont été Invoqués Spécialement depuis l\'Extra Deck sont détruits au combat ou par un effet de carte de l\'adversaire : vous pouvez Invoquer Spécialement cette carte depuis le Cimetière (si elle y était lorsque le monstre a été détruit) ou main (même si elle n\'y était pas), mais bannissez-la lorsqu\'elle quitte le Terrain. Si cette carte est envoyée au Cimetière comme Matériel pour l\'Invocation Lien d\'un Monstre Lien Cyberse min. Link-2 : vous pouvez ajouter 1 Magie Normale \"Salamangrande\" depuis votre Deck à votre main. Vous ne pouvez utiliser chaque effet de \"Salamangrande Fennec\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-4.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-4.jpg'),
('dane-fr005', 'Dragon du Dépassement', 'TÉNÈBRES', 1, '[ Dragon / Effet ]', 'ATK 0', 'DEF 0', 'Lorsqu\'un ou plusieurs monstres sur le Terrain sont détruits par un effet de carte (sauf durant la Damage Step) : vous pouvez Invoquer Spécialement cette carte depuis votre main, puis, si min. 2 monstres sur le Terrain ont été détruits par l\'effet de carte, vous pouvez Invoquer Spécialement 1 \"Jeton du Dépassement\" (Dragon/TÉNÈBRES/Niveau 1/ATK 0/DEF 0). Vous ne pouvez utiliser cet effet de \"Dragon du Dépassement\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-5.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-5.jpg'),
('dane-fr006', 'Fifinellag Altergeist', 'TÉNÈBRES', 2, '[ Magicien / Syntoniseur / Effet ]', 'ATK 0', 'DEF 1000', 'Les monstres contrôlés par votre adversaire ne peuvent pas cibler les monstres \"Altergeist\" que vous contrôlez (\"Fifinellag Altergeist\" exclu) avec une attaque, et aussi, votre adversaire ne peut pas cibler de monstres \"Altergeist\" que vous contrôlez (\"Fifinellag Altergeist\" exclu) avec des effets de carte.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-6.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-6.jpg'),
('dane-fr007', 'Dinolutteur Escrimamenchi', 'TERRE', 6, '[ Dinosaure / Effet ]', 'ATK 2200', 'DEF 0', 'Si vous contrôlez un monstre \"Dinolutteur\", vous pouvez Invoquer Normalement cette carte sans Sacrifice. Durant votre tour, si votre adversaire Invoque Spécialement un ou plusieurs monstres tant que cette carte est dans votre Cimetière (sauf durant la Damage Step) : vous pouvez cibler 1 monstre \"Dinolutteur\" de max. Niveau 4 dans votre Cimetière ; Invoquez-le Spécialement, puis ajoutez cette carte à votre main. Vous ne pouvez utiliser cet effet de \"Dinolutteur Escrimamenchi\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-7.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-7.jpg'),
('dane-fr008', 'Dinolutteur Coelasilat', 'TERRE', 2, '[ Dinosaure / Syntoniseur / Effet ]', 'ATK 100', 'DEF 800', 'Si vous ne contrôlez aucun monstre, vous pouvez Invoquer Spécialement cette carte (depuis votre main). Si elle est Invoquée de cette façon, cette carte ne peut pas être utilisée comme Matériel Lien, sauf pour l\'Invocation Lien d\'un monstre \"Dinolutteur\". Vous ne pouvez Invoquer Spécialement \"Dinolutteur Coelasilat\" qu\'une fois par Duel de cette façon.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-8.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-8.jpg'),
('dane-fr009', 'Dinolutteur Martial Anga', 'TERRE', 5, '[ Dinosaure / Effet ]', 'ATK 1600', 'DEF 0', 'Durant le calcul des dommages, lorsque votre monstre \"Dinolutteur\" combat un monstre avec une ATK supérieure ou égale (Effet Rapide) : vous pouvez envoyer cette carte depuis votre main au Cimetière ; votre monstre combattant ne peut pas être détruit par ce combat, et aussi, terminez la Battle Phase après la Damage Step. Une fois par tour, durant la End Phase, si cette carte est dans le Cimetière parce qu\'elle y a été envoyée pour activer cet effet ce tour, et que votre adversaire contrôle plus de monstres que vous : vous pouvez Invoquer Spécialement cette carte.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-9.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-9.jpg'),
('dane-fr010', 'Piochemain - HÉROS de la Destinée', 'TÉNÈBRES', 4, '[ Guerrier / Effet ]', 'ATK 1600', 'DEF 800', 'Si cette carte est Invoquée Spécialement par l\'effet d\'un monstre \"HÉROS\" : vous pouvez faire piocher 1 carte à chaque joueur. Durant la prochaine Standby Phase après que cette carte a été envoyée au Cimetière : vous pouvez Invoquer Spécialement cette carte depuis votre Cimetière, mais bannissez-la lorsqu\'elle quitte le Terrain. Vous ne pouvez utiliser chaque effet de \"Piochemain - HÉROS de la Destinée\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-10.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-10.jpg'),
('dane-fr011', 'Réflecteur Psionique', 'TÉNÈBRES', 1, '[ Psychique / Syntoniseur / Effet ]', 'ATK 400', 'DEF 300', 'Si cette carte est Invoquée Normalement ou Spécialement : vous pouvez ajouter 1 \"Activation Mode Assaut\", ou 1 carte qui liste spécifiquement \"Activation Mode Assaut\" dans son texte (\"Réflecteur Psionique\" exclu) depuis votre Deck à votre main. Vous pouvez révéler 1 \"Activation Mode Assaut\" dans votre main, puis ciblez 1 monstre dans votre Cimetière qui liste spécifiquement \"Activation Mode Assaut\" dans son texte (\"Réflecteur Psionique\" exclu) ; Invoquez-le Spécialement, et si vous le faites, augmentez son Niveau de 1 à 4. Vous ne pouvez utiliser chaque effet de \"Réflecteur Psionique\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-11.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-11.jpg'),
('dane-fr012', 'Sentinelle d\'Assaut', 'TERRE', 4, '[ Bête-Guerrier / Effet ]', 'ATK 1600', 'DEF 800', 'Vous pouvez Sacrifier cette carte ; Invoquez Spécialement 1 monstre depuis votre main ou Deck qui liste spécifiquement \"Activation Mode Assaut\" dans son texte (\"Sentinelle d\'Assaut\" exclu), et aussi, vous ne pouvez pas Invoquer Spécialement de monstres (Monstres Synchro exclus) depuis l\'Extra Deck le reste de ce tour. Vous pouvez cibler 1 monstre face recto que vous contrôlez ; révélez 1 Monstre Synchro depuis votre Extra Deck, et si vous le faites, les Type et Attribut du monstre ciblé deviennent les mêmes que ceux du monstre révélé jusqu\'à la fin de ce tour. Vous ne pouvez utiliser chaque effet de \"Sentinelle d\'Assaut\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-12.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-12.jpg'),
('dane-fr013', 'Canon Hallebarde T.G./Mode Assaut', 'TERRE', 12, '[ Machine / Effet ]', 'ATK 4500', 'DEF 4500', 'Ni Invocable Normalement ni Posable Normalement. Uniquement Invocable Spécialement avec \"Activation Mode Assaut\". Vous ne pouvez utiliser chacun des effets suivants de \"Canon Hallebarde T.G./Mode Assaut\" qu\'une fois par tour.\n●Lorsque votre adversaire va Invoquer un monstre (Effet Rapide) : vous pouvez annuler l\'Invocation, et si vous le faites, bannissez le monstre et tous les monstres Invoqués Spécialement contrôlés par votre adversaire.\n●Lorsque cette carte sur le Terrain est détruite : vous pouvez cibler 1 \"Canon Hallebarde T.G.\" dans votre Cimetière ; Invoquez-le Spécialement, en ignorant ses conditions d\'Invocation.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-13.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-13.jpg'),
('dane-fr014', 'Force White Super Quantum', 'LUMIÈRE', 7, '[ Elfe / Effet ]', 'ATK 2400', 'DEF 2400', 'Vous pouvez envoyer 1 monstre non-LUMIÈRE \"Super Quant\" depuis votre main ou Terrain face recto au Cimetière ; Invoquez Spécialement cette carte depuis votre main en Position de Défense. Lorsque cette carte est Invoquée Normalement ou Spécialement : vous pouvez envoyer 1 monstre \"Super Quant\" depuis votre Deck au Cimetière, et si vous le faites, l\'Attribut et Niveau de cette carte deviennent les mêmes que ceux du monstre. Si cette carte est envoyée au Cimetière : vous pouvez ajouter 1 \"Fée Alphan Super Quantique\" depuis votre Deck ou Cimetière à votre main. Vous ne pouvez utiliser chaque effet de \"Force White Super Quantum\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-14.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-14.jpg'),
('dane-fr015', 'Dame de la Néo Cloche de Feu', 'FEU', 4, '[ Pyro / Effet ]', 'ATK 1600', 'DEF 200', '(Effet Rapide) : vous pouvez envoyer 1 monstre FEU depuis votre main au Cimetière, puis ciblez 1 carte dans le Cimetière de votre adversaire ; bannissez la carte. Si une carte est bannie depuis le Cimetière de votre adversaire, tant que vous contrôlez ce monstre (sauf durant la Damage Step) : vous pouvez envoyer 1 monstre FEU avec max. 200 DEF (\"Dame de la Néo Cloche de Feu\" exclu) depuis votre Deck au Cimetière. Vous ne pouvez utiliser chaque effet de \"Dame de la Néo Cloche de Feu\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-15.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-15.jpg'),
('dane-fr016', 'Filo, Messager Mercefourrure', 'VENT', 1, '[ Bête Ailée / Effet ]', 'ATK 0', 'DEF 0', 'Durant votre Main Phase : vous pouvez Invoquer Spécialement 1 monstre \"Mercefourrure\" (\"Filo, Messager Mercefourrure\" exclu) depuis votre main. Si un monstre \"Mercefourrure\" est Invoqué Spécialement sur votre Terrain tant que vous contrôlez ce monstre (sauf durant la Damage Step) : vous pouvez cibler 1 monstre \"Mercefourrure\" dans votre Cimetière ; Invoquez-le Spécialement en Position de Défense, mais placez-le au-dessous du Deck s\'il quitte le Terrain. Vous ne pouvez utiliser chaque effet de \"Filo, Messager Mercefourrure\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-16.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-16.jpg'),
('dane-fr017', 'Yuki-Musume, Mayakashi de la Glace', 'EAU', 1, '[ Zombie / Effet ]', 'ATK 0', 'DEF 1900', 'Si vous contrôlez une carte \"Mayakashi\" (\"Yuki-Musume, Mayakashi de la Glace\" exclu) tant que cette carte est dans votre main ou Cimetière : vous pouvez Invoquer Spécialement cette carte, puis envoyez 1 monstre Zombie depuis votre Deck au Cimetière. Vous ne pouvez utiliser cet effet de \"Yuki-Musume, Mayakashi de la Glace\" qu\'une fois par tour. Vous ne pouvez pas Invoquer Spécialement de monstres (monstres \"Mayakashi\" exclus) depuis l\'Extra Deck.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-17.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-17.jpg'),
('dane-fr018', 'Idlee l\'Incarnation, Chevalier du Cauchemar', 'TÉNÈBRES', 9, '[ Elfe / Effet ]', 'ATK 2100', 'DEF 2100', 'Les monstres de Niveau 9 que vous contrôlez ne peuvent pas être détruits par des effets de carte. Vous ne pouvez utiliser chacun des effets suivants de \"Idlee l\'Incarnation, Chevalier du Cauchemar\" qu\'une fois par tour.\n●Si la somme des Classifications Lien des monstres sur le Terrain est min. 8 (Effet Rapide) : vous pouvez Invoquer Spécialement cette carte depuis votre main.\n●Si cette carte est Invoquée Spécialement, tant que votre adversaire contrôle plus de Monstres Lien que vous : vous pouvez envoyer tous les Monstres Lien sur le Terrain au Cimetière.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-18.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-18.jpg'),
('dane-fr019', 'Mardark de la Dragarde de l\'Héritage du Monde', 'VENT', 9, '[ Dragon / Effet ]', 'ATK 2600', 'DEF 3000', 'Tous les monstres contrôlés par votre adversaire perdent 500 ATK/DEF pour chaque monstre Dragon que vous contrôlez. Vous ne pouvez utiliser chacun des effets suivants de \"Mardark de la Dragarde de l\'Héritage du Monde\" qu\'une fois par tour.\n●Vous pouvez bannir 2 Monstres Normaux depuis votre main ou Cimetière ; Invoquez Spécialement cette carte depuis votre main.\n●Si cette carte sur le Terrain est détruite au combat ou par un effet de carte : vous pouvez ajouter 1 monstre de Niveau 9 de Type et Attribut d\'origine différents de cette carte depuis votre Cimetière à votre main.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-19.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-19.jpg'),
('dane-fr020', 'Deus X-Krawler', 'TERRE', 9, '[ Insecte / Flip / Effet ]', 'ATK 2000', 'DEF 3000', 'Lorsque votre adversaire active une carte ou un effet qui cible ce monstre face verso (Effet Rapide) : vous pouvez changer cette carte en Position de Défense face recto ; annulez l\'activation, et si vous le faites, détruisez la carte. Après que cette carte a été retournée face recto, tant qu\'elle est dans la Zone Monstre, annulez tous les effets de monstre activés sur le Terrain de votre adversaire. Si cette carte sur le Terrain est détruite au combat ou par un effet de carte : vous pouvez ajouter 1 monstre de Niveau 9 de Type et Attribut d\'origine différents de cette carte depuis votre Deck à votre main. Vous ne pouvez utiliser cet effet de \"Deus X-Krawler\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-20.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-20.jpg'),
('dane-fr021', 'Omni Dragon Brotaur', 'TÉNÈBRES', 1, '[ Dragon / Effet ]', 'ATK 0', 'DEF 0', 'Si un monstre que vous contrôlez est détruit au combat ou par un effet de carte de l\'adversaire : vous pouvez Invoquer Spécialement cette carte depuis le Cimetière (si elle y était lorsque le monstre a été détruit) ou main (même si elle n\'y était pas), mais bannissez-la lorsqu\'elle quitte le Terrain. Si cette carte est Invoquée Spécialement : vous pouvez cibler 1 monstre face recto sur le Terrain ; défaussez 1 carte, et si vous le faites, ajoutez 1 monstre depuis votre Deck à votre main, du même Type et Attribut que la cible, mais de nom différent. Vous ne pouvez utiliser chaque effet de \"Omni Dragon Brotaur\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-21.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-21.jpg'),
('dane-fr022', 'Traître du Chaos', 'TÉNÈBRES', 6, '[ Démon / Effet ]', 'ATK 2000', 'DEF 2000', 'Si cette carte est dans votre Cimetière : vous pouvez bannir 1 monstre LUMIÈRE et 1 monstre TÉNÈBRES (\"Traître du Chaos\" exclu) depuis votre Cimetière ; Invoquez Spécialement cette carte en Position de Défense, mais bannissez-la lorsqu\'elle quitte le Terrain. Si cette carte est Invoquée Spécialement : vous pouvez cibler 1 carte dans le Cimetière de votre adversaire ; bannissez-la. Vous ne pouvez utiliser chaque effet de \"Traître du Chaos\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-22.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-22.jpg'),
('dane-fr023', 'Nuage Bruyant le Serpent Tempête', 'EAU', 5, '[ Reptile / Effet ]', 'ATK 0', 'DEF 2000', 'Ni Invocable Normalement ni Posable Normalement. Doit d\'abord être Invoquée Spécialement (depuis votre main) en bannissant 1 monstre FEU et 1 monstre VENT depuis votre Cimetière. Vous ne pouvez utiliser chacun des effets suivants de \"Nuage Bruyant le Serpent Tempête\" qu\'une fois par tour.\n●Vous pouvez bannir 1 monstre FEU depuis votre Cimetière, puis ciblez 1 monstre contrôlé par votre adversaire ; détruisez le monstre, et si vous le faites, cette carte gagne une ATK égale à l\'ATK d\'origine du monstre détruit.\n●Vous pouvez bannir 1 monstre VENT depuis votre Cimetière, puis ciblez 1 carte dans la Zone Magie & Piège de votre adversaire ; détruisez-la.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-23.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-23.jpg'),
('dane-fr024', 'Glissedauphin Xyz', 'EAU', 4, '[ Serpent de Mer / Effet ]', 'ATK 1200', 'DEF 1800', 'Si un Monstre Xyz est Invoqué Spécialement sur votre Terrain (sauf durant la Damage Step) : vous pouvez Invoquer Spécialement cette carte depuis votre main. Si un ou plusieurs Monstres Xyz sont Invoqués Spécialement sur votre Terrain tant que cette carte est dans votre Cimetière, sauf le tour où cette carte a été envoyée à votre Cimetière (sauf durant la Damage Step) : vous pouvez cibler 1 de ces Monstres Xyz ; attachez-lui cette carte comme Matériel. Vous ne pouvez utiliser chaque effet de \"Glissedauphin Xyz\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-24.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-24.jpg'),
('dane-fr025', 'Fixétoileur', 'VENT', 4, '[ Bête Ailée / Effet ]', 'ATK 1000', 'DEF 1500', 'Cette carte gagne un effet selon votre Zone Monstre Main dans laquelle elle est.\n●La plus à gauche : Augmentez son Niveau de 4.\n●La plus à droite : Augmentez son Niveau de 3.\n●Centre : Augmentez son Niveau de 2.\n●Autres : Augmentez son Niveau de 1.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-25.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-25.jpg'),
('dane-fr026', 'Fille Fantôme et Cornouiller Effrayant', 'EAU', 3, '[ Zombie / Syntoniseur / Effet ]', 'ATK 0', 'DEF 1800', 'Durant chaque tour, sauf la End Phase (Effet Rapide) : vous pouvez défausser cette carte ; ce tour, appliquez cet effet. Vous ne pouvez utiliser cet effet de \"Fille Fantôme et Cornouiller Effrayant\" qu\'une fois par tour.\n●Chaque fois que votre adversaire Invoque Spécialement un ou plusieurs Monstres à Effet durant la Main Phase ou Battle Phase, vous gagnez des LP égaux à l\'ATK du monstre. Si vous n\'avez pas gagné de LP par cet effet, vos LP sont divisés par deux durant la End Phase.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-26.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-26.jpg'),
('dane-fr027', 'Handigalop', 'TERRE', 1, '[ Bête / Effet ]', 'ATK 0', 'DEF 0', 'Ne peut pas attaquer directement. Gagne une ATK égale à la différence entre vos LP et ceux de votre adversaire. Si vos LP sont supérieurs à ceux de votre adversaire, vous recevez les dommages de combat que votre adversaire aurait dû recevoir des combats impliquant cette carte attaquante à la place.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-27.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-27.jpg'),
('dane-fr028', 'Empereur Maju Garzett', 'TÉNÈBRES', 9, '[ Démon / Effet ]', 'ATK 0', 'DEF 0', 'Ni Invocable Normalement ni Posable Normalement. Uniquement Invocable Spécialement (depuis votre main) en Sacrifiant 3 monstres. L\'ATK de cette carte devient la somme des ATK d\'origine des monstres Sacrifiés. Votre adversaire ne peut activer ni de cartes ni d\'effets durant la Battle Phase.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-28.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-28.jpg'),
('dane-fr029', 'Dunk Cupide', 'LUMIÈRE', 4, '[ Elfe / Effet ]', 'ATK 1800', 'DEF 600', 'Non destructible au combat avec un monstre, sauf si le monstre a un Niveau supérieur. Une fois par tour, durant votre Standby Phase : vous pouvez augmenter le Niveau de cette carte de 1.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-29.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-29.jpg'),
('dane-fr030', 'Créaltar, l\'Initiateur de la Lutincantation', 'LUMIÈRE', 10, '[ Démon / Rituel / Effet ]', 'ATK 3000', 'DEF 3000', 'Vous pouvez Invoquer Rituellement cette carte avec \"Commencement de Lutincantation\". Durant la Main Phase (Effet Rapide) : vous pouvez révéler cette carte dans votre main ; défaussez 1 carte, puis Invoquez Spécialement un nombre de monstres \"Lutincantation\" depuis votre Cimetière dont le Niveau total est égal à 10, mais mélangez-les dans le Deck durant la End Phase. Vous ne pouvez utiliser cet effet de \"Créaltar, l\'Initiateur de la Lutincantation\" qu\'une fois par tour. Les monstres non-Rituel \"Lutincantation\" que vous contrôlez gagnent 2000 ATK, mais leurs effets sont annulés.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-30.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-30.jpg'),
('dane-fr031', 'Dinolutteur Chimère T Rexlutte', 'TERRE', 8, '[ Dinosaure / Fusion / Effet ]', 'ATK 3500', 'DEF 0', '1 Monstre Lien \"Dinolutteur\" + 1 monstre \"Dinolutteur\"\nSi cette carte combat, votre adversaire ne peut pas activer de Cartes Magie/Piège jusqu\'à la fin de la Damage Step. Si cette carte attaque un monstre en Position de Défense, infligez des dommages de combat perçants. Les monstres de votre adversaire ne peuvent pas cibler de monstres (celui-ci exclu) avec une attaque. Si cette carte détruit un monstre au combat : elle gagne 500 ATK. Si cette carte est détruite par un effet de carte : détruisez tous les monstres en Position d\'Attaque de votre adversaire.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-31.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-31.jpg'),
('dane-fr032', 'Dominance - HÉROS de la Destinée', 'TÉNÈBRES', 10, '[ Guerrier / Fusion / Effet ]', 'ATK 2900', 'DEF 2600', '3 monstres \"HÉROS de la Destinée\"\nDurant votre Main Phase : vous pouvez regarder les 5 cartes du dessus de votre Deck ou du Deck de votre adversaire, puis placez-les au-dessus du Deck dans l\'ordre de votre choix. Lorsque cette carte détruit un monstre de l\'adversaire au combat : vous pouvez piocher 1 carte. Si cette carte Invoquée par Fusion est détruite au combat ou par un effet de carte : vous pouvez cibler 3 monstres \"HÉROS de la Destinée\" de max. Niveau 9 de noms différents dans votre Cimetière ; Invoquez-les Spécialement. Vous ne pouvez utiliser chaque effet de \"Dominance - HÉROS de la Destinée\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-32.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-32.jpg'),
('dane-fr033', 'Almarduke de la Dragarde du Calice du Monde', 'VENT', 9, '[ Dragon / Fusion / Effet ]', 'ATK 3000', 'DEF 2600', '3 Monstres Lien\nDoit d\'abord être Invoquée par Fusion, ou Spécialement depuis votre Extra Deck en Sacrifiant les cartes ci-dessus que vous contrôlez (auquel cas vous n\'utilisez pas \"Polymérisation\"). Cette carte peut attaquer une fois tous les monstres contrôlés par votre adversaire. Lorsqu\'une attaque impliquant cette carte et un Monstre Lien de l\'adversaire est déclarée : vous pouvez bannir 1 Monstre Lien avec la même Classification Lien que le monstre depuis votre Terrain ou Cimetière ; détruisez le monstre de l\'adversaire, et si vous le faites, infligez des dommages à votre adversaire égaux à son ATK d\'origine.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-33.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-33.jpg'),
('dane-fr034', 'Dragvirion Altergeist', 'TÉNÈBRES', 6, '[ Magicien / Synchro / Effet ]', 'ATK 2200', 'DEF 1200', '1 Syntoniseur + 1+ monstre non-Syntoniseur\nLorsqu\'un monstre Invoqué Spécialement de l\'adversaire déclare une attaque : vous pouvez renvoyer 1 monstre \"Altergeist\" que vous contrôlez à la main ; annulez l\'attaque. Si cette carte est Sacrifiée et envoyée au Cimetière : vous pouvez Invoquer Spécialement cette carte. Vous ne pouvez utiliser chaque effet de \"Dragvirion Altergeist\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-34.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-34.jpg'),
('dane-fr035', 'Dinolutteur Giga Spinosavate', 'TERRE', 8, '[ Dinosaure / Synchro / Effet ]', 'ATK 3000', 'DEF 0', '1 Syntoniseur Dinosaure + 1+ monstre non-Syntoniseur\nSi cette carte combat, votre adversaire ne peut pas activer de Cartes Magie/Piège jusqu\'à la fin de la Damage Step. Les monstres de votre adversaire ne peuvent pas cibler de monstres (celui-ci exclu) avec une attaque. Une fois par tour : vous pouvez cibler 1 monstre contrôlé par votre adversaire ; détruisez-le. Si cette carte va être détruite au combat ou par un effet de carte, vous pouvez détruire 1 carte que vous contrôlez à la place.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-35.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-35.jpg'),
('dane-fr036', 'Ib la Justicière du Calice du Monde', 'EAU', 5, '[ Magicien / Synchro / Syntoniseur / Effet ]', 'ATK 1800', 'DEF 2100', '1 Syntoniseur + 1+ monstre non-Syntoniseur\nPour l\'Invocation Synchro de cette carte, vous pouvez traiter 1 Monstre Normal \"Calice du Monde\" que vous contrôlez comme un Syntoniseur. Vous ne pouvez utiliser chacun des effets suivants de \"Ib la Justicière du Calice du Monde\" qu\'une fois par tour.\n●Si cette carte est Invoquée par Synchronisation : vous pouvez ajouter 1 carte \"Héritage du Monde\" depuis votre Deck à votre main.\n●Si cette carte Invoquée par Synchronisation est envoyée depuis le Terrain au Cimetière : vous pouvez Invoquer Spécialement 1 monstre \"Calice du Monde\" (\"Ib la Justicière du Calice du Monde\" exclu) depuis votre Deck ou Cimetière.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-36.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-36.jpg'),
('dane-fr037', 'Dragon eXceed Pare-Feu', 'TÉNÈBRES', NULL, '[ Cyberse / Xyz / Effet ]', 'ATK 2500', 'DEF 2000', '2+ monstres de Niveau 4\nCette carte Invoquée par Xyz gagne 500 ATK x la somme des Classifications Lien des Monstres Lien liés à cette carte. Vous pouvez détacher 2 Matériels de cette carte, puis ciblez 1 Monstre Lien Cyberse Link-4 dans votre Cimetière ; Invoquez-le Spécialement sur votre Terrain afin qu\'il pointe cette carte, et aussi, vous ne pouvez ni Invoquer Spécialement d\'autres monstres ni attaquer directement le reste de ce tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-37.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-37.jpg'),
('dane-fr038', 'Lusterrex Bête Méca Super Quantique', 'LUMIÈRE', NULL, '[ Machine / Xyz / Effet ]', 'ATK 2700', 'DEF 1900', '2 monstres de Niveau 7\nNe peut pas attaquer sauf si elle a du Matériel. Une fois par tour : vous pouvez détacher 1 Matériel de cette carte, puis ciblez 1 Monstre à Effet sur le Terrain ; jusqu\'à la fin de ce tour, annulez les effets du monstre face recto. Ceci est un Effet Rapide si cette carte a \"Force White Super Quantum\" comme Matériel. Une fois par tour : vous pouvez attacher 1 monstre \"Super Quantum\" depuis votre main ou Terrain à cette carte comme Matériel.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-38.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-38.jpg'),
('dane-fr039', 'Dingirsu, l\'Orcust de l\'Étoile du Berger', 'TÉNÈBRES', NULL, '[ Machine / Xyz / Effet ]', 'ATK 2600', 'DEF 2100', '2 monstres de Niveau 8\nVous ne pouvez Invoquer Spécialement un ou plusieurs \"Dingirsu, l\'Orcust de l\'Étoile du Berger\" qu\'une fois par tour. Vous pouvez aussi Invoquer par Xyz cette carte en utilisant un Monstre Lien \"Orcust\" que vous contrôlez comme Matériel. Si une ou plusieurs cartes que vous contrôlez vont être détruites au combat ou par un effet de carte, vous pouvez détacher 1 Matériel de cette carte à la place. Si cette carte est Invoquée Spécialement : vous pouvez activer 1 de ces effets ;\n●Envoyez 1 carte contrôlée par votre adversaire au Cimetière.\n●Attachez 1 de vos monstres Machine bannis à cette carte comme Matériel.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-39.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-39.jpg'),
('dane-fr040', 'Professeur Glassoufflé Magidolce', 'TERRE', NULL, '[ Elfe / Xyz / Effet ]', 'ATK 1800', 'DEF 2500', '2 monstres \"Magidolce\" de Niveau 4\n(Effet Rapide) : vous pouvez détacher 1 Matériel de cette carte, puis ciblez 1 monstre \"Magidolce\" sur le Terrain ; ce tour, le monstre face recto n\'est pas affecté par des effets de monstre (ses propres effets exclus). Si une carte \"Magidolce\" est envoyée à votre Cimetière tant que cette carte est sur le Terrain (sauf durant la Damage Step) : vous pouvez mélanger max. 2 cartes depuis les Cimetières dans les Decks. Vous ne pouvez utiliser chaque effet de \"Professeur Glassoufflé Magidolce\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-40.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-40.jpg'),
('dane-fr041', 'Rappeleur Cyberse', 'LUMIÈRE', NULL, '[ Cyberse / Xyz / Effet ]', 'ATK 1800', 'DEF 800', '2 monstres de Niveau 3\nVous pouvez détacher 1 Matériel de cette carte, puis ciblez 1 Magie/Piège \"Cynet\" dans votre Cimetière ; ajoutez-le à votre main. Si cette carte Invoquée par Xyz est détruite au combat, ou détruite par un effet de carte de l\'adversaire tant qu\'elle est dans la Zone Monstre de son propriétaire : vous pouvez Invoquer Spécialement 2 monstres Cyberse de Niveau 4 de noms différents depuis votre Deck, mais leurs effets sont annulés. Vous ne pouvez utiliser chaque effet de \"Rappeleur Cyberse\" qu\'une fois par tour, et aussi, vous ne pouvez pas Invoquer Spécialement de monstres (monstres Cyberse exclus) depuis l\'Extra Deck le tour où vous activez un effet de cette carte.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-41.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-41.jpg'),
('dane-fr042', 'Dragon Derringereux', 'TÉNÈBRES', NULL, '[ Dragon / Lien / Effet ]', 'ATK 1600', 'DEF -', '2 monstres TÉNÈBRES Dragon\nUne fois par tour, durant la End Phase de votre adversaire : vous pouvez cibler 1 monstre en Position d\'Attaque contrôlé par votre adversaire qui n\'a pas déclaré d\'attaque ce tour ; détruisez-le, et si vous le faites, infligez des dommages à votre adversaire égaux à l\'ATK d\'origine du monstre. Si un ou plusieurs monstres \"Rokkette\" sont Invoqués Spécialement sur votre Terrain, tant que cette carte est dans votre Cimetière (sauf durant la Damage Step) : vous pouvez Invoquer Spécialement cette carte, mais bannissez-la lorsqu\'elle quitte le Terrain. Vous ne pouvez utiliser chaque effet de \"Dragon Derringereux\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-42.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-42.jpg'),
('dane-fr043', 'Dinolutteur Terra Parkourio', 'TERRE', NULL, '[ Dinosaure / Lien / Effet ]', 'ATK 1000', 'DEF -', '2 monstres \"Dinolutteur\"\nSi vous activez \"Dino Lutte Mondiale\" : vous pouvez cibler 1 monstre \"Dinolutteur\" dans votre Cimetière ; ajoutez-le à votre main. Si cette carte est envoyée au Cimetière comme Matériel Lien : vous pouvez cibler 1 monstre \"Dinolutteur\" dans votre Cimetière ; Invoquez-le Spécialement en Position de Défense, mais annulez ses effets, et aussi, vous ne pouvez pas Invoquer Spécialement de monstres (monstres \"Dinolutteur\" exclus) le reste de ce tour. Vous ne pouvez utiliser chaque effet de \"Dinolutteur Terra Parkourio\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-43.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-43.jpg'),
('dane-fr044', 'Gouki L\'Ogre Lame', 'TERRE', NULL, '[ Guerrier / Lien / Effet ]', 'ATK 2400', 'DEF -', '2+ monstres \"Gouki\"\nGagne 300 ATK pour chaque monstre pointé par cette carte. Une fois par tour : vous pouvez Sacrifier 1 monstre pointé par cette carte sur le Terrain ; durant chaque Battle Phase ce tour, cette carte peut faire une seconde attaque.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-44.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-44.jpg'),
('dane-fr045', 'Gouki L\'Ogre Solide', 'TERRE', NULL, '[ Guerrier / Lien / Effet ]', 'ATK 2400', 'DEF -', '2+ monstres \"Gouki\"\nNon destructible ni au combat ni par des effets de carte tant qu\'elle pointe un monstre \"Gouki\". Une fois par tour (Effet Rapide) : vous pouvez cibler 1 monstre \"Gouki\" (\"Gouki L\'Ogre Solide\" exclu) dans votre Zone Monstre Main ; déplacez le monstre que vous contrôlez dans votre Zone Monstre Main pointée par cette carte.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-45.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-45.jpg'),
('dane-fr046', 'Croiseur de la Croix, HÉROS Xtra', 'TÉNÈBRES', NULL, '[ Guerrier / Lien / Effet ]', 'ATK 1600', 'DEF -', '2 monstres Guerrier\nSi cette carte est Invoquée par Lien : vous pouvez cibler 1 monstre \"HÉROS de la Destinée\" dans votre Cimetière ; Invoquez-le Spécialement. Vous pouvez Sacrifier 1 monstre \"HÉROS de la Destinée\" ; ajoutez 1 monstre \"HÉROS\" de nom différent depuis votre Deck à votre main. Vous ne pouvez utiliser chaque effet de \"Croiseur de la Croix, HÉROS Xtra\" qu\'une fois par tour, et aussi, vous ne pouvez pas Invoquer Spécialement de monstres (monstres \"HÉROS\" exclus) le tour où vous activez un effet de cette carte.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-46.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-46.jpg'),
('dane-fr047', 'Magna Exploseur Roi Méca Super Quantique Néo', 'LUMIÈRE', NULL, '[ Machine / Lien / Effet ]', 'ATK 2500', 'DEF -', '2+ Monstres à Effet (un monstre \"Super Quant\" inclus)\nCette carte Invoquée par Lien ne peut pas être détruite par des effets de carte de votre adversaire. Chaque fois qu\'un ou plusieurs Monstres Xyz \"Super Quant\" de nom différent des cartes que vous contrôlez sont Invoqués Spécialement depuis l\'Extra Deck dans des zones pointées par cette carte : piochez 1 carte. Si un ou plusieurs Monstres Xyz face recto pointés par cette carte sont détruits au combat ou par un effet de carte de l\'adversaire : vous pouvez Invoquer Spécialement 1 monstre \"Super Quant\" depuis votre Deck du même Attribut d\'origine qu\'1 de ces Monstres Xyz détruits. Vous ne pouvez utiliser cet effet de \"Magna Exploseur Roi Méca Super Quantique Néo\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-47.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-47.jpg'),
('dane-fr048', 'Avramax Mekk-Chevalier Croisédia', 'LUMIÈRE', NULL, '[ Cyberse / Lien / Effet ]', 'ATK 3000', 'DEF -', '2+ monstres Invoqués Spécialement depuis l\'Extra Deck\nTant que cette carte Invoquée par Lien est sur le Terrain, votre adversaire ne peut pas cibler cette carte avec des effets de carte, et aussi, ses monstres ne peuvent pas cibler de monstres (celui-ci exclu) avec une attaque. Une fois par combat, durant le calcul des dommages, si cette carte combat un monstre Invoqué Spécialement (Effet Rapide) : durant ce calcul des dommages uniquement, vous pouvez faire gagner à cette carte une ATK égale à l\'ATK du monstre de l\'adversaire. Si cette carte Invoquée par Lien que vous contrôlez est envoyée à votre Cimetière par une carte de l\'adversaire : vous pouvez mélanger 1 carte sur le Terrain dans le Deck.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-48.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-48.jpg'),
('dane-fr049', 'Démiurge Théurgéquipe des Équipements du Monde', 'TÉNÈBRES', NULL, '[ Cyberse / Lien / Effet ]', 'ATK 3500', 'DEF -', '3 monstres de min. Niveau 5\nNon utilisable comme Matériel Lien. Cette carte Invoquée par Lien n\'est pas affectée par les effets d\'autres monstres. Vous ne pouvez utiliser chacun des effets suivants de \"Démiurge Théurgéquipe des Équipements du Monde\" qu\'une fois par tour.\n●Durant votre Main Phase, si vous contrôlez cette carte qui a été Invoquée par Lien en utilisant 3 monstres qui avaient 3 Types et Attributs différents sur le Terrain : vous pouvez détruire toutes les autres cartes sur le Terrain.\n●Si votre adversaire Invoque Spécialement un ou plusieurs monstres depuis l\'Extra Deck (sauf durant la Damage Step) : vous pouvez Invoquer Spécialement 1 monstre \"Héritage du Monde\" depuis votre Deck.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-49.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-49.jpg'),
('dane-fr050', 'Puzzlomino, le Glisse-Effaceur', 'LUMIÈRE', NULL, '[ Magicien / Lien / Effet ]', 'ATK 1300', 'DEF -', '2 monstres de Niveaux différents\nSi un monstre est Invoqué Spécialement face recto dans une zone pointée par cette carte tant que vous contrôlez ce monstre (sauf durant la Damage Step) : vous pouvez déclarer un Niveau de 1 à 8 ; jusqu\'à la fin du tour, le monstre devient de ce Niveau. Vous pouvez cibler 2 monstres de même Niveau (1 sur chaque Terrain) ; détruisez-les. Vous ne pouvez utiliser chaque effet de \"Puzzlomino, le Glisse-Effaceur\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-50.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-50.jpg'),
('dane-fr051', 'Véhicolonne Amphibie Ambuleine', 'FEU', NULL, '[ Machine / Lien / Effet ]', 'ATK 2600', 'DEF -', '2+ Monstres à Effet\nGagne 200 ATK pour chaque Monstre Lien dans les Cimetières. Vous ne pouvez utiliser chacun des effets suivants de \"Véhicolonne Amphibie Ambuleine\" qu\'une fois par tour.\n●Si cette carte est détruite : vous pouvez cibler 1 monstre de min. Link-3 dans l\'un des Cimetières ; Invoquez-le Spécialement.\n●Si un ou plusieurs monstres de min. Link-3 sur le Terrain sont détruits au combat ou par un effet de carte tant que cette carte est dans votre Cimetière : vous pouvez bannir cette carte depuis votre Cimetière ; détruisez 1 carte sur le Terrain.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-51.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-51.jpg'),
('dane-fr052', 'Cynet Minage', 'MAGIE', NULL, NULL, NULL, NULL, 'Envoyez 1 carte depuis votre main au Cimetière ; ajoutez 1 monstre Cyberse de max. Niveau 4 depuis votre Deck à votre main. Vous ne pouvez activer qu\'1 \"Cynet Minage\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-52.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-52.jpg'),
('dane-fr053', 'Remècurrence Salamangrande', 'MAGIE', NULL, NULL, NULL, NULL, 'Ciblez 2 monstres \"Salamangrande\" dans votre Cimetière de noms différents ; ajoutez-les à votre main. Si cette carte Posée est détruite par un effet de carte et envoyée au Cimetière : vous pouvez ajouter 1 Magie/Piège \"Salamangrande\" (\"Remècurrence Salamangrande\" exclu) depuis votre Deck à votre main. Vous ne pouvez utiliser chaque effet de \"Remècurrence Salamangrande\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-53.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-53.jpg'),
('dane-fr054', 'Fusion Dino Tyran', 'MAGIE', NULL, NULL, NULL, NULL, 'Invoquez par Fusion 1 monstre \"Dinolutteur\" depuis votre Extra Deck, en utilisant des monstres que vous contrôlez comme Matériel Fusion. Si vous le faites, la première fois que le monstre face recto sur le Terrain va être détruit au combat ou par un effet de carte, il n\'est pas détruit.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-54.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-54.jpg'),
('dane-fr055', 'Fusion de la Destinée', 'MAGIE', NULL, NULL, NULL, NULL, 'Invoquez par Fusion 1 Monstre Fusion qui liste un monstre \"HÉROS de la Destinée\" comme Matériel depuis votre Extra Deck, en utilisant des monstres depuis votre main ou Deck comme Matériel Fusion, mais détruisez-le durant la End Phase du prochain tour, et aussi, vous ne pouvez pas Invoquer Spécialement de monstres (monstres TÉNÈBRES \"HÉROS\" exclus) le reste de ce tour après la résolution de cette carte. Vous ne pouvez activer qu\'1 \"Fusion de la Destinée\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-55.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-55.jpg'),
('dane-fr056', 'Mode Assaut Zéro', 'MAGIE', NULL, NULL, NULL, NULL, 'Sacrifiez 1 Monstre Synchro ; Invoquez Spécialement 1 monstre \"/Mode Assaut\" depuis votre main dont le nom inclut le nom du monstre Sacrifié. (Ceci est traité comme une Invocation Spéciale avec \"Activation Mode Assaut\".) Durant votre Main Phase : vous pouvez bannir cette carte depuis votre Cimetière ; Posez 1 \"Activation Mode Assaut\" directement depuis votre main ou Deck. Il peut être activé ce tour. Vous ne pouvez utiliser chaque effet de \"Mode Assaut Zéro\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-56.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-56.jpg'),
('dane-fr057', 'Appel de Demande Alphan Super Quantique', 'MAGIE', NULL, NULL, NULL, NULL, 'Si un monstre \"Super Quant\" que vous contrôlez est détruit au combat : Invoquez Spécialement 1 Monstre Xyz \"Bête Méca Super Quantique\" depuis votre Extra Deck, puis vous pouvez Invoquer Spécialement 1 monstre \"Super Quantum\" depuis votre main, Deck ou Cimetière, qui est spécifiquement listé dans le texte du Monstre Xyz, mais annulez ses effets. Vous ne pouvez activer qu\'1 \"Appel de Demande Alphan Super Quantique\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-57.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-57.jpg'),
('dane-fr058', 'Hiver Mayakashi', 'MAGIE', NULL, NULL, NULL, NULL, 'Les monstres contrôlés par votre adversaire perdent 100 ATK/DEF pour chaque monstre \"Mayakashi\" de nom différent dans votre Cimetière. Vous ne pouvez utiliser qu\'1 des effets suivants de \"Hiver Mayakashi\" par tour, et uniquement une fois le tour.\n●Envoyez cette carte et 1 monstre \"Mayakashi\" que vous contrôlez au Cimetière ; piochez 1 carte.\n●Bannissez cette carte et 1 monstre Zombie depuis votre Cimetière, puis ciblez 1 monstre \"Mayakashi\" dans votre Cimetière ; Invoquez-le Spécialement.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-58.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-58.jpg'),
('dane-fr059', 'Aérosol Nuagien', 'MAGIE', NULL, NULL, NULL, NULL, 'Défaussez 1 monstre \"Nuagien\", puis ciblez 1 monstre face recto sur le Terrain ; placez un nombre de Compteurs Brume sur la cible égal à son Niveau. Vous pouvez bannir cette carte et 1 monstre \"Nuagien\" depuis votre Cimetière ; Invoquez Spécialement 1 monstre \"Nuagien\" depuis votre Deck. Vous ne pouvez utiliser qu\'1 effet de \"Aérosol Nuagien\" par tour, et uniquement une fois le tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-59.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-59.jpg'),
('dane-fr060', 'Monstruosité de l\'Héritage du Monde', 'MAGIE', NULL, NULL, NULL, NULL, 'Activez 1 de ces effets.\n●Invoquez Spécialement 1 monstre de Niveau 9 depuis votre main.\n●Ciblez 1 monstre de Niveau 9 que vous contrôlez ; Invoquez Spécialement 2 monstres de Niveau 9 avec chacun un Type et Attribut d\'origine différents du monstre face recto ciblé, et de noms différents les uns des autres, depuis votre Deck, mais ces 2 monstres ne peuvent pas attaquer, et aussi, détruisez-les durant la End Phase.\nVous ne pouvez activer qu\'1 \"Monstruosité de l\'Héritage du Monde\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-60.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-60.jpg'),
('dane-fr061', 'Réincarnation Dragarde', 'MAGIE', NULL, NULL, NULL, NULL, 'Invoquez par Fusion 1 Monstre Fusion depuis votre Extra Deck, en bannissant des Matériels Fusion listés sur celui-ci, qui sont tous des Monstres Lien, depuis votre Terrain ou Cimetière. Vous ne pouvez activer qu\'1 \"Réincarnation Dragarde\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-61.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-61.jpg'),
('dane-fr062', 'Testament Croisédia', 'MAGIE', NULL, NULL, NULL, NULL, 'Activez 1 de ces effets.\n●Ce tour, votre adversaire ne peut activer ni de cartes ni d\'effets en réponse à l\'activation des effets de votre monstre \"Croisédia\".\n●Après le calcul des dommages, si votre Monstre Lien \"Croisédia\" détruit un monstre de l\'adversaire au combat : piochez un nombre de cartes égal à la Classification Lien de votre monstre.\nVous ne pouvez activer qu\'1 \"Testament Croisédia\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-62.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-62.jpg'),
('dane-fr063', 'Thanatose de Lutincantation', 'MAGIE', NULL, NULL, NULL, NULL, 'Lorsque cette carte est activée : vous pouvez révéler 1 monstre \"Lutincantation\" dans votre main et Invoquer Spécialement 2 monstres du nom du monstre depuis votre Deck, puis mélangez le monstre révélé dans le Deck. Une fois par tour, si un Monstre Rituel est Invoqué Spécialement sur votre Terrain : vous pouvez cibler 1 carte sur le Terrain (sauf durant la Damage Step) ; détruisez-la. Vous ne pouvez activer qu\'1 \"Thanatose de Lutincantation\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-63.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-63.jpg'),
('dane-fr064', 'Hymne Funèbre du Dragon Perdu', 'MAGIE', NULL, NULL, NULL, NULL, 'Activez cette carte en déclarant 1 nom de carte. Chaque fois que la carte déclarée ou son effet est activé, divisez par deux les LP de son propriétaire immédiatement après sa résolution. Durant la End Phase, si cette carte a divisé par deux les LP d\'un joueur ce tour, envoyez cette carte au Cimetière. Tant que votre adversaire contrôle un monstre, cette carte ne peut pas être détruite par des effets de carte.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-64.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-64.jpg'),
('dane-fr065', 'Mine Mystique', 'MAGIE', NULL, NULL, NULL, NULL, 'Si votre adversaire contrôle plus de monstres que vous, votre adversaire ne peut ni activer d\'effets de monstre ni déclarer d\'attaque. Si vous contrôlez plus de monstres que votre adversaire, vous ne pouvez ni activer d\'effets de monstre ni déclarer d\'attaque. Une fois par tour, durant la End Phase, si chaque joueur contrôle le même nombre de monstres : détruisez cette carte.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-65.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-65.jpg'),
('dane-fr066', 'Mordschlag', 'MAGIE', NULL, NULL, NULL, NULL, 'Équipable uniquement à un monstre Invoqué/Posé Normalement que vous contrôlez. Il n\'est pas affecté par les effets activés de monstres Invoqués Spécialement de votre adversaire. Durant le calcul des dommages, si le monstre équipé combat un monstre Invoqué Spécialement de l\'adversaire : durant ce calcul des dommages uniquement, le monstre de l\'adversaire perd une ATK/DEF égales à l\'ATK d\'origine du monstre équipé.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-66.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-66.jpg'),
('dane-fr067', 'Doublure', 'MAGIE', NULL, NULL, NULL, NULL, 'Sacrifiez 1 monstre, puis ciblez 1 monstre dans le Cimetière de votre adversaire du même Type et Attribut d\'origine ; Invoquez-le Spécialement sur votre Terrain. Vous ne pouvez activer qu\'1 \"Doublure\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-67.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-67.jpg'),
('dane-fr068', 'Permutation de Paquet', 'MAGIE', NULL, NULL, NULL, NULL, 'Ciblez 1 Monstre non-Lien face recto que vous contrôlez et 1 Monstre Lien contrôlé par votre adversaire ; échangez le contrôle de ces monstres. Vous ne pouvez activer qu\'1 \"Permutation de Paquet\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-68.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-68.jpg'),
('dane-fr069', 'Rocher Hanté Altergeist', 'PIÈGE', NULL, NULL, NULL, NULL, 'Si cette carte a été Posée par l\'effet d\'une carte \"Altergeist\", vous pouvez l\'activer le tour où elle a été Posée. Lorsque cette carte est activée : envoyez 1 monstre \"Altergeist\" depuis votre main au Cimetière. Lorsque votre adversaire active une Carte Piège (sauf durant la Damage Step) : vous pouvez envoyer 1 monstre \"Altergeist\" depuis votre main au Cimetière ; annulez l\'effet, et si vous le faites, détruisez la carte. Vous ne pouvez utiliser chaque effet de \"Rocher Hanté Altergeist\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-69.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-69.jpg');
INSERT INTO `Cartes` (`Num`, `Nom`, `Attribut`, `Niveau`, `Types`, `Attaque`, `Defense`, `Description`, `image_miniature`, `image_grande`) VALUES
('dane-fr070', 'Tactiques D', 'PIÈGE', NULL, NULL, NULL, NULL, 'Durant la Standby Phase : vous pouvez faire gagner 400 ATK à tous les monstres \"HÉROS\" que vous contrôlez (même si cette carte quitte le Terrain). Si \"Soldat Dragon de l\'Ultime Destinée\" ou un ou plusieurs monstres \"HÉROS de la Destinée\" de min. Niveau 8 sont Invoqués Spécialement sur votre Terrain (sauf durant la Damage Step) : vous pouvez bannir 1 carte depuis la main (au hasard), Terrain ou Cimetière de votre adversaire. Si cette carte dans la Zone Magie & Piège est détruite par un effet de carte : vous pouvez ajouter 1 monstre \"HÉROS de la Destinée\" depuis votre Deck à votre main. Vous ne pouvez utiliser chaque effet de \"Tactiques D\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-70.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-70.jpg'),
('dane-fr071', 'Redémarrage d\'Assaut', 'PIÈGE', NULL, NULL, NULL, NULL, 'Sacrifiez 1 monstre \"/Mode Assaut\" ; Invoquez Spécialement 1 monstre \"/Mode Assaut\" depuis votre Deck de nom différent en Position de Défense, en ignorant ses conditions d\'Invocation. Vous pouvez bannir cette carte depuis votre Cimetière, puis ciblez un nombre de votre choix de cartes dans votre Cimetière, de noms différents, qui sont \"Activation Mode Assaut\" et/ou qui liste spécifiquement \"Activation Mode Assaut\" dans leur texte (\"Redémarrage d\'Assaut\" exclu) ; mélangez-les dans le Deck. Vous ne pouvez utiliser chaque effet de \"Redémarrage d\'Assaut\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-71.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-71.jpg'),
('dane-fr072', 'Union Super Quantique - Magnaformation', 'PIÈGE', NULL, NULL, NULL, NULL, 'Durant votre Main Phase 1, votre adversaire ne peut pas cibler de cartes \"Super Quant\" sur le Terrain avec des effets de carte. Vous pouvez cibler 1 Monstre Xyz \"Super Quant\" que vous contrôlez ; attachez-lui 1 autre monstre face recto que vous contrôlez comme Matériel. Vous ne pouvez utiliser cet effet de \"Union Super Quantique - Magnaformation\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-72.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-72.jpg'),
('dane-fr073', 'Magie de Mousquet - Couronne Malhonnête', 'PIÈGE', NULL, NULL, NULL, NULL, 'Vous ne pouvez contrôler qu\'1 \"Magie de Mousquet - Couronne Malhonnête\". Durant la Main Phase : vous pouvez Invoquer Spécialement 1 monstre \"Magie de Mousquet\" depuis votre main, et si vous le faites, si la Zone Monstre Main de votre adversaire dans la colonne actuelle du monstre est inutilisée, la zone ne peut pas être utilisée jusqu\'à la fin de ce tour (même si cette carte quitte le Terrain). Vous ne pouvez utiliser cet effet de \"Magie de Mousquet - Couronne Malhonnête\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-73.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-73.jpg'),
('dane-fr074', 'Peinture Arc-en-Ciel Météorologique', 'PIÈGE', NULL, NULL, NULL, NULL, 'Vous ne pouvez contrôler qu\'1 \"Peinture Arc-en-Ciel Météorologique\". Les Monstres à Effet \"Météorologique\" dans vos Zones Monstre Main de la colonne de cette carte et de ses colonnes adjacentes gagnent cet effet.\n●Si votre adversaire contrôle un monstre (Effet Rapide) : vous pouvez bannir cette carte ; Invoquez Spécialement 1 monstre \"Météorologique\" de nom différent depuis votre Deck, et aussi, vous ne pouvez pas Invoquer Spécialement d\'autres monstres depuis le Deck le reste de ce tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-74.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-74.jpg'),
('dane-fr075', 'Crescendo Orcust', 'PIÈGE', NULL, NULL, NULL, NULL, 'Lorsqu\'une Carte Magie/Piège ou un effet de monstre est activé tant que vous contrôlez un Monstre Lien \"Orcust\" : annulez l\'activation, et si vous le faites, bannissez la carte. Vous pouvez bannir cette carte depuis votre Cimetière ; ajoutez 1 de vos monstres TÉNÈBRES Machine qui est banni ou dans votre Deck à votre main. Vous ne pouvez pas Invoquer Spécialement de monstres (monstres TÉNÈBRES Machine exclus) le tour où vous activez cet effet. Vous ne pouvez utiliser qu\'1 effet de \"Crescendo Orcust\" par tour, et uniquement une fois le tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-75.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-75.jpg'),
('dane-fr076', 'Effondrement de l\'Héritage du Monde', 'PIÈGE', NULL, NULL, NULL, NULL, 'Vous pouvez bannir 1 monstre \"Héritage du Monde\" depuis votre main, Cimetière ou Terrain face recto, puis ciblez 1 Monstre Lien sur le Terrain ; il gagne une ATK égale à l\'ATK d\'origine du monstre banni (même si cette carte quitte le Terrain). Si un ou plusieurs Monstres Lien que vous contrôlez sont détruits au combat ou par un effet de carte de l\'adversaire tant que cette carte est dans votre Cimetière : vous pouvez bannir cette carte ; Invoquez Spécialement 1 Monstre Lien Cyberse depuis votre Cimetière. Vous ne pouvez utiliser chaque effet de \"Effondrement de l\'Héritage du Monde\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-76.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-76.jpg'),
('dane-fr077', 'Cliffhanger de l\'Héritage du Monde', 'PIÈGE', NULL, NULL, NULL, NULL, 'Lorsqu\'une attaque impliquant 2 Monstres Lien est déclarée : mélangez tous les monstres sur le Terrain et dans les Cimetières dans les Decks. Le reste de ce tour après la résolution de cette carte, aucun joueur ne peut Invoquer par Lien.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-77.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-77.jpg'),
('dane-fr078', 'Trappe de Chaîne', 'PIÈGE', NULL, NULL, NULL, NULL, 'Lorsque votre adversaire active un effet de monstre en réponse à l\'activation d\'une carte ou d\'un effet : annulez l\'effet de l\'adversaire, puis, votre adversaire peut bannir 1 carte depuis sa main ou Deck du même nom d\'origine que la carte annulée. S\'il ne l\'a pas fait, vous pouvez bannir 1 carte au hasard depuis sa main.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-78.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-78.jpg'),
('dane-fr079', 'Répression', 'PIÈGE', NULL, NULL, NULL, NULL, 'Activez en ciblant 1 monstre face recto contrôlé par votre adversaire ; prenez le contrôle du monstre. Tant que vous contrôlez le monstre, il ne peut ni attaquer ni activer d\'effets. Lorsque le monstre quitte le Terrain, détruisez cette carte.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-79.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-79.jpg'),
('dane-fr080', 'Effet de Bonhomme de Neige', 'PIÈGE', NULL, NULL, NULL, NULL, 'Ciblez 1 monstre face recto que vous contrôlez ; jusqu\'à la fin de ce tour, il gagne une ATK égale à la somme des ATK d\'origine des autres monstres que vous contrôlez. Il ne peut pas attaquer directement durant le tour où vous activez cette carte. Vous ne pouvez activer qu\'1 \"Effet de Bonhomme de Neige\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-80.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-80.jpg'),
('dane-fr081', 'Dégime', 'PIÈGE', NULL, NULL, NULL, NULL, 'Lancez un dé à six faces. Appliquez cet effet selon le tour.\n●Durant votre tour : bannissez un nombre de cartes depuis votre Cimetière égal au résultat. Puis, si le résultat est 1, envoyez aussi 6 cartes du dessus de votre Deck au Cimetière.\n●Durant le tour de votre adversaire : envoyez un nombre de cartes du dessus de votre Deck au Cimetière égal au résultat. Puis, si le résultat est 6, bannissez aussi 1 carte depuis votre Cimetière.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-81.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-81.jpg'),
('dane-fr082', 'Boudragon Boueux', 'TÉNÈBRES', 6, '[ Dragon / Synchro / Effet ]', 'ATK 500', 'DEF 2200', '1 Syntoniseur + 1+ monstre non-Syntoniseur\nCette carte peut être utilisée comme substitut pour 1 Matériel Fusion dont le nom est listé spécifiquement sur la Carte Monstre Fusion, mais les autres Matériels Fusion doivent être corrects. Durant votre Main Phase, si vous contrôlez cette carte Invoquée par Synchronisation : vous pouvez Invoquer par Fusion 1 Monstre Fusion depuis votre Extra Deck, en utilisant des monstres que vous contrôlez (cette carte incluse) comme Matériel Fusion. Vous ne pouvez utiliser cet effet de \"Boudragon Boueux\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-82.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-82.jpg'),
('dane-fr083', 'Chaînes de Saryuja', 'PIÈGE', NULL, NULL, NULL, NULL, 'Ciblez 1 Monstre Lien contrôlé par votre adversaire ou dans son Cimetière ; piochez un nombre de cartes égal à sa Classification Lien, puis, si vous avez min. 2 cartes dans votre main, placez 2 cartes depuis votre main au-dessous de votre Deck dans l\'ordre de votre choix. Vous ne pouvez activer qu\'1 \"Chaînes de Saryuja\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-83.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-83.jpg'),
('dane-fr084', 'Danger ! Excitation ! Mystère !', 'MAGIE', NULL, NULL, NULL, NULL, 'Défaussez 1 monstre \"Danger !\" de min. Niveau 5 ; ajoutez 1 monstre \"Danger !\" de max. Niveau 4 depuis votre Deck à votre main. Le reste de ce tour après la résolution de cette carte, vous ne pouvez pas Invoquer Spécialement de monstres (monstres \"Danger !\" exclus). Vous ne pouvez activer qu\'1 \"Danger ! Excitation ! Mystère !\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-84.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-84.jpg'),
('dane-fr085', 'Danger ! Pieds de Force !', 'MAGIE', NULL, NULL, NULL, NULL, 'Équipable uniquement à un monstre \"Danger !\". Il gagne 800 ATK/DEF. Il ne peut pas être détruit par des effets de carte. Il peut faire max. 2 attaques sur des monstres durant chaque Battle Phase.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-85.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-85.jpg'),
('dane-fr086', 'Vous êtes en Danger !', 'PIÈGE', NULL, NULL, NULL, NULL, 'Révélez 3 monstres \"Danger !\" de noms différents depuis votre Deck, votre adversaire en prend 1 au hasard pour vous à Invoquer Spécialement, et vous mélangez les cartes restantes dans le Deck. Durant la End Phase, détruisez le monstre Invoqué Spécialement. Vous ne pouvez activer qu\'1 \"Vous êtes en Danger !\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-86.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-86.jpg'),
('dane-fr087', 'Valkyrie-Fünfte', 'LUMIÈRE', 2, '[ Elfe / Effet ]', 'ATK 800', 'DEF 1200', 'Les monstres \"Valkyrie-\" que vous contrôlez gagnent 200 ATK pour chaque monstre banni de votre adversaire. Si vous contrôlez un monstre \"Valkyrie-\" (\"Valkyrie-Fünfte\" exclu) : vous pouvez envoyer 1 Magie/Piège depuis votre Deck au Cimetière. Vous ne pouvez utiliser cet effet de \"Valkyrie-Fünfte\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-87.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-87.jpg'),
('dane-fr088', 'Valkyrie-Erda', 'LUMIÈRE', 8, '[ Elfe / Effet ]', 'ATK 2000', 'DEF 2200', 'Vous ne pouvez contrôler qu\'1 \"Valkyrie-Erda\". Tant que vous contrôlez cette carte, Invoquée Spécialement par l\'effet d\'une carte \"Valkyrie-\", tous les monstres face recto contrôlés par votre adversaire perdent 1000 ATK. Les cartes détruites au combat ou par un effet de carte qui vont être envoyées au Cimetière de votre adversaire sont bannies à la place.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-88.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-88.jpg'),
('dane-fr089', 'Valkyrie-Attelage', 'VENT', 3, '[ Elfe / Union / Effet ]', 'ATK 500', 'DEF 1000', 'Une fois par tour, vous pouvez SOIT : ciblez 1 monstre Elfe que vous contrôlez ; équipez cette carte à la cible, SOIT : déséquipez cette carte et Invoquez-la Spécialement. Si le monstre équipé va être détruit au combat ou par un effet de carte, détruisez cette carte à la place. Lorsque le monstre équipé déclare une attaque : vous pouvez lui faire gagner 500 ATK. (Ce gain d\'ATK reste même si cette carte quitte le Terrain.)', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-89.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-89.jpg'),
('dane-fr090', 'Valkyrie-Étreinte', 'MAGIE', NULL, NULL, NULL, NULL, 'Si tous les monstres que vous contrôlez sont des monstres \"Valkyrie-\" : ciblez 1 monstre \"Valkyrie-\" en Position d\'Attaque que vous contrôlez et 1 monstre face recto contrôlé par votre adversaire ; changez votre monstre en Position de Défense, et si vous le faites, bannissez le monstre de l\'adversaire. Vous ne pouvez pas Invoquer Spécialement de monstres (monstres \"Valkyrie-\" exclus) le tour où vous activez cette carte. Vous ne pouvez activer qu\'1 \"Valkyrie-Étreinte\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-90.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-90.jpg'),
('dane-fr091', 'Ailes de Pégase', 'MAGIE', NULL, NULL, NULL, NULL, 'Si vous avez un monstre Union dans votre Cimetière : ciblez un nombre de votre choix de monstres \"Valkyrie-\" que vous contrôlez ; ces monstres peuvent attaquer directement ce tour, mais s\'ils le font en utilisant cet effet, leurs dommages de combat infligés à votre adversaire sont divisés par deux.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-91.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-91.jpg'),
('dane-fr092', 'Écran de Flamme Bleue', 'PIÈGE', NULL, NULL, NULL, NULL, 'Tant que vous contrôlez un monstre \"Valkyrie-\", les monstres contrôlés par votre adversaire avec max. 2000 ATK ne peuvent pas attaquer. Si cette carte en votre possession est détruite par un effet de carte de l\'adversaire : vous pouvez Invoquer Spécialement 1 monstre \"Valkyrie-\" de min. Niveau 5 depuis votre main ou Deck.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-92.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-92.jpg'),
('dane-fr093', 'Numéro 5 : Dragon Chimère de la Mort', 'TÉNÈBRES', NULL, '[ Dragon / Xyz / Effet ]', 'ATK 0', 'DEF 0', '2+ monstres de Niveau 5\nGagne 1000 ATK pour chaque Matériel qui lui est attaché. Cette carte avec du Matériel peut attaquer une fois tous les monstres contrôlés par votre adversaire. À la fin de la Battle Phase, si cette carte a combattu : vous pouvez activer un des effets suivants.\n●Ciblez 1 monstre dans votre Cimetière ; attachez-lui cette carte comme Matériel.\n●Ciblez 1 carte dans le Cimetière de votre adversaire ; placez-la au-dessus de son Deck.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-93.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-93.jpg'),
('dane-fr094', 'Numéro XX : Infini Utopique des Ténèbres', 'TÉNÈBRES', NULL, '[ Guerrier / Xyz / Effet ]', 'ATK 4000', 'DEF 4000', '2+ monstres de Niveau 10\nLorsqu\'un monstre est détruit au combat et envoyé au Cimetière : vous pouvez détacher 1 Matériel de cette carte, puis ciblez le monstre ; Invoquez-le Spécialement sur votre Terrain en Position de Défense. Vous pouvez cibler 1 autre monstre face recto Invoqué Spécialement que vous contrôlez ; gagnez des LP égaux à son ATK d\'origine. Vous ne pouvez utiliser chaque effet de \"Numéro XX : Infini Utopique des Ténèbres\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-94.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-94.jpg'),
('dane-fr095', 'Sirènemure Abyssalacia', 'EAU', NULL, '[ Serpent de Mer / Lien / Effet ]', 'ATK 1600', 'DEF -', '2 monstres Poisson, Serpent de Mer et/ou Aqua\nLes monstres pointés par cette carte gagnent 500 ATK/DEF. Vous ne pouvez utiliser chacun des effets suivants de \"Sirènemure Abyssalacia\" qu\'une fois par tour.\n●Durant le tour de votre adversaire (Effet Rapide) : vous pouvez envoyer 1 carte depuis votre main au Cimetière ; ajoutez 1 monstre \"Sirènemure\" depuis votre Deck à votre main.\n●Si cette carte en possession de son propriétaire est détruite par une attaque ou effet de carte de l\'adversaire : vous pouvez envoyer 1 monstre EAU depuis votre Deck au Cimetière, puis ciblez 1 monstre EAU dans votre Cimetière ; Invoquez-le Spécialement en Position de Défense.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-95.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-95.jpg'),
('dane-fr096', 'Cherubini, Ange Ébène des Abysses Ardents', 'TÉNÈBRES', NULL, '[ Elfe / Lien / Effet ]', 'ATK 500', 'DEF -', '2 monstres de Niveau 3\nLes monstres pointés par cette carte ne peuvent pas être détruits par des effets de carte. Si cette carte va être détruite au combat ou par un effet de carte de l\'adversaire, vous pouvez envoyer 1 autre carte que vous contrôlez au Cimetière à la place. Vous pouvez envoyer 1 monstre de Niveau 3 depuis votre Deck au Cimetière, puis ciblez 1 monstre \"Abysses Ardents\" sur le Terrain ; jusqu\'à la fin de ce tour, il gagne une ATK/DEF égale à l\'ATK/DEF du monstre envoyé au Cimetière. Vous ne pouvez utiliser cet effet de \"Cherubini, Ange Ébène des Abysses Ardents\" qu\'une fois par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-96.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-96.jpg'),
('dane-fr097', 'Driftrapide', 'MAGIE', NULL, NULL, NULL, NULL, 'Si vous contrôlez exactement 1 Syntoniseur et aucun autre monstre : Invoquez Spécialement 1 monstre \"Vitesseroid\" de max. Niveau 4 depuis votre Deck. Aucun joueur ne peut activer ni de cartes ni d\'effets lorsque le monstre est Invoqué Spécialement.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-97.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-97.jpg'),
('dane-fr098', 'Arrêt Pendule', 'MAGIE', NULL, NULL, NULL, NULL, 'Si vous avez min. 3 Monstres Pendule face recto de noms différents dans votre Extra Deck : piochez 2 cartes. Le reste de ce tour après la résolution de cette carte, vous ne pouvez pas ajouter de cartes depuis le Deck à votre main.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-98.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-98.jpg'),
('dane-fr099', 'Sauvetage Poisson à Chair Blanche', 'MAGIE', NULL, NULL, NULL, NULL, 'Vous pouvez cibler 1 monstre Poisson dans votre Cimetière ; ajoutez-le à votre main. Vous ne pouvez utiliser cet effet de \"Sauvetage Poisson à Chair Blanche\" qu\'une fois par tour. Si cette carte en votre possession est détruite par un effet de carte de l\'adversaire et envoyée à votre Cimetière : prenez 1 monstre Poisson depuis votre Deck, et soit ajoutez-le à votre main soit Invoquez-le Spécialement.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-99.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-99.jpg'),
('dane-fr100', 'Souvenirs d\'Espoir', 'MAGIE', NULL, NULL, NULL, NULL, 'Piochez un nombre de cartes égal au nombre de Monstres Xyz \"Numéro\" de noms différents que vous contrôlez. Vous ne pouvez activer qu\'1 \"Souvenirs d\'Espoir\" par tour.', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-100.jpg', 'http://www.otk-expert.fr/cartes/yugioh_ext/DANE/DANE-100.jpg');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
